# Generated by Django 6.0.3 on 2026-03-24 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('orientacion', models.CharField(choices=[('BASICO', 'Ciclo Básico'), ('ECONOMIA', 'Economía y Administración'), ('NATURALES', 'Ciencias Naturales'), ('SOCIALES', 'Ciencias Sociales'), ('INFORMATICA', 'Informática'), ('ARTE', 'Arte')], default='BASICO', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tema', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('es_director', models.BooleanField(default=False)),
                ('es_admin_sistema', models.BooleanField(default=False)),
                ('es_profesor', models.BooleanField(default=False)),
                ('es_preceptor', models.BooleanField(default=False)),
                ('es_alumno', models.BooleanField(default=False)),
                ('rol_primario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.curso')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.institucion')),
            ],
            options={
                'unique_together': {('nombre', 'curso', 'institucion')},
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='informes.division')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='LibroDeTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre_dictado', models.IntegerField(choices=[(1, '1° Trim'), (2, '2° Trim'), (3, '3° Trim'), (4, '4° Trim')])),
                ('fecha_dictado', models.DateField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.materia')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.tema')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_anual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.alumno')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_unidad', models.IntegerField()),
                ('nombre_unidad', models.CharField(max_length=200)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.materia')),
            ],
        ),
        migrations.AddField(
            model_name='tema',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_unidad', to='informes.unidad'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.institucion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Preceptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.institucion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='informes.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='InformeTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField(choices=[(1, '1° Trim'), (2, '2° Trim'), (3, '3° Trim'), (4, '4° Trim')])),
                ('d_reconoce', models.BooleanField(default=False)),
                ('d_utiliza', models.BooleanField(default=False)),
                ('d_contextualiza', models.BooleanField(default=False)),
                ('a_reconoce', models.BooleanField(default=False)),
                ('a_utiliza', models.BooleanField(default=False)),
                ('a_contextualiza', models.BooleanField(default=False)),
                ('fecha_trimestre_completada', models.BooleanField(default=False)),
                ('trabajo_integrador_entregado', models.BooleanField(default=False)),
                ('porcentaje_rubrica_docente', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_rubrica_alumno', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('porcentaje_final_trimestre', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('registro_avance', models.CharField(choices=[('ALCANZADO', 'Alcanzado'), ('EN_PROCESO', 'Sigue en proceso')], max_length=20)),
                ('observaciones', models.CharField(max_length=255)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.alumno')),
                ('temas_evaluados', models.ManyToManyField(related_name='informes_pertenecientes', to='informes.librodetema')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.materia')),
            ],
            options={
                'unique_together': {('alumno', 'materia', 'trimestre')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo_lectivo', models.IntegerField(default=2026)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.division')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.materia')),
                ('docente', models.ForeignKey(limit_choices_to={'rol_primario': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, to='informes.usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Docente',
                'verbose_name_plural': 'Asignaciones de Docentes',
                'unique_together': {('materia', 'division', 'ciclo_lectivo')},
            },
        ),
    ]
