# Generated by Django 6.0.3 on 2026-03-25 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemasTrimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.IntegerField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.asignaciondocente')),
                ('temas_dados', models.ManyToManyField(blank=True, to='informes.tema')),
            ],
            options={
                'unique_together': {('asignacion', 'trimestre')},
            },
        ),
    ]
