# Generated by Django 6.0.3 on 2026-03-25 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_temastrimestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informetrimestral',
            name='a_contextualiza',
        ),
        migrations.RemoveField(
            model_name='informetrimestral',
            name='a_reconoce',
        ),
        migrations.RemoveField(
            model_name='informetrimestral',
            name='a_utiliza',
        ),
        migrations.RemoveField(
            model_name='informetrimestral',
            name='porcentaje_rubrica_alumno',
        ),
        migrations.RemoveField(
            model_name='informetrimestral',
            name='temas_evaluados',
        ),
        migrations.AlterField(
            model_name='informetrimestral',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='informetrimestral',
            name='registro_avance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='DetalleEvaluacionTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluado_fecha', models.BooleanField(default=False)),
                ('tpi', models.BooleanField(default=False)),
                ('reconoce', models.BooleanField(default=False)),
                ('utiliza', models.BooleanField(default=False)),
                ('contextualiza', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ALCANZADO', 'Alcanzado'), ('EN_PROCESO', 'En proceso')], max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_temas', to='informes.informetrimestral')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.librodetema')),
            ],
        ),
    ]
