# Generated by Django 6.0.3 on 2026-03-25 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0003_remove_informetrimestral_a_contextualiza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleevaluaciontema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informes.tema'),
        ),
        migrations.DeleteModel(
            name='SeguimientoFinal',
        ),
    ]
