# Generated by Django 6.0.3 on 2026-03-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0004_alter_detalleevaluaciontema_tema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_1_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_1_habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_2_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_2_habilitado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_3_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_3_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
