# Generated by Django 6.0.3 on 2026-03-29 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0005_asignaciondocente_trimestre_1_finalizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_4_finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='trimestre_4_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
